module.exports = 
[
    {
        email : "valentin@gmail.com",
        password : "1234",
        first_name : "valentin",
        last_name : "carrichon",
        tel_number : "0626711720",
        age : 22,
        adress : "rue du test",
        city_id :"2",
        astrologicalsign_id : "2",
        animals:[1,2,9,12],
        animes:[1,6,11,18],
        cars:[15],
        destinations:[1,2],
        drinks:[3,7,15],
        filmtypes:[2,7,8],
        foods:[1,3,5,14],
        musictypes:[6,9,11],
        sports:[1,2,9],
        videogames:[1,2,4,7]
    },
    {
        email : "lucas@gmail.com",
        password : "1234",
        first_name : "lucas",
        last_name : "guillotin",
        tel_number : "0645128954",
        age : 21,
        adress : "rue du test",
        city_id :"3",
        astrologicalsign_id : "3",
        animals:[2,3,12],
        animes:[3,8,14],
        cars:[9,15],
        destinations:[1,5,12],
        drinks:[2,7],
        filmtypes:[1,5,9],
        foods:[2,4,16],
        musictypes:[11,15],
        sports:[10],
        videogames:[2,3,6,10]
    },
    {
        email : "test@latest.com",
        password : "latest",
        first_name : "test",
        last_name : "latest",
        tel_number : "0769853654",
        age : 58,
        adress : "5 avenue de l'Infini",
        city_id :"28",
        astrologicalsign_id : "7",
        animals: [1,4,8],
        animes:[1,8,17],
        cars:[2,15],
        destinations:[5,6],
        drinks:[10,14],
        filmtypes:[2,11],
        foods:[1,6,7],
        musictypes:[2,3,4],
        sports:[2,8,9],
        videogames:[6,8]
    },
    {
        email : "yoann@singer.com",
        password : "yoann",
        first_name : "yoann",
        last_name : "singer",
        tel_number : "0123456789",
        age : 22,
        adress : "23 cours des cons",
        city_id :"14",
        astrologicalsign_id : "5",
        animals: [2,8,13],
        animes:[3,6,17],
        cars:[8],
        destinations:[3,9],
        drinks:[5,14],
        filmtypes:[3,13],
        foods:[1,6,7],
        musictypes:[2,14,16],
        sports:[1],
        videogames:[6,7]
    },
    {
        email : "alexandre@mazeau.com",
        password : "mazeau",
        first_name : "alexandre",
        last_name : "mazeau",
        tel_number : "0856953274",
        age : 21,
        adress : "29 quai des kassos",
        city_id :"14",
        astrologicalsign_id : "4",
        animals: [4,9,12],
        animes:[1],
        cars:[3,14],
        destinations:[12],
        drinks:[11],
        filmtypes:[12,15],
        foods:[2,7],
        musictypes:[4,9,15],
        sports:[3,8],
        videogames:[4,14]
    },

    
]