name: github-ci
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image:  node:latest
    steps:
      - run: npm install
    
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
      - run: pm2 start pm2.json
      - run: npm run fixtures
      - run: npm run test
