name: github-ci
on: [push]

jobs:

  install:
    runs-on: ubuntu-latest 

    services:
      mysql:
        image: mysql:5.7
        env: 
          DB_URL: mysql://root:root@localhost:${{ job.services.mysql.ports[3306] }}/webservices?serverVersion=5.7
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install
      env:
        CI: true

    - name: Execute unit tests via Mocha
      run: npm run test
      
      