name: github-ci
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      with:
        node-version: '12.x'
      - run: npm install
    
  # build:
  #   runs-on: node-latest
  #   steps:
  #     - npm install
  #     - run: npm run build --if-present
  #     - run: pm2 start pm2.json
  #     - run: npm run fixtures
  #     - run: npm run test
