name: github-ci
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
    
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run build --if-present
      - run: pm2 start pm2.json
      - run: npm run fixtures
      - run: npm run test
