name: github-ci
on: [push]

jobs:

  install:
    runs-on: ubuntu-latest 

    services:
      mysql:
        image: mysql:5.7
        ports:
            - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: webservices
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install
      env:
        CI: true

    - name: Verify MySQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

    - name: Execute unit tests via Mocha
      run: npm run test
      env: 
        DATABASEB_URL: mysql://root:root@localhost:3306/webservices?serverVersion=5.7
      